[package]
name = "mcapq"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
include.workspace = true
description = "Machine-readable MCAP inspection CLI."
readme = "README.md"

[[bin]]
name = "mcapq"
path = "src/main.rs"

[dependencies]
clap.workspace = true
mcapdecode.workspace = true
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149", features = ["preserve_order"] }

[dev-dependencies]
mcap = "0.24.0"
