[package]
name = "mcapdecode"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
include.workspace = true
description = "MCAP decoding library with optional Arrow integration, protobuf, and ROS 2 decoders."
readme = "README.md"

[dependencies]
mcapdecode-arrow = { workspace = true, optional = true }
mcapdecode-core.workspace = true
mcapdecode-reader.workspace = true
arrow = { workspace = true, optional = true }

[features]
default = ["protobuf", "ros2idl", "ros2msg"]
arrow = ["dep:arrow", "dep:mcapdecode-arrow"]
protobuf = ["mcapdecode-reader/protobuf"]
ros2idl = ["mcapdecode-reader/ros2idl"]
ros2msg = ["mcapdecode-reader/ros2msg"]

[dev-dependencies]
criterion.workspace = true
mcap = "0.24.0"
mcapbench.workspace = true
memmap2 = "0.9.10"

[[bench]]
name = "decoder"
harness = false
required-features = ["protobuf", "ros2idl", "ros2msg"]

[[bench]]
name = "reader"
harness = false
required-features = ["ros2idl"]

[[bench]]
name = "arrow"
harness = false
required-features = ["arrow", "ros2idl"]
